// This file is generated by Slice Machine. Update with care!

import LoginPage from './LoginPage';
import MySlice from './MySlice';

export {
	LoginPage,
	MySlice,
};

export const components = {
	login_page: LoginPage,
	my_slice: MySlice,
};
